[package]

name = "concurrency_project"
version = "0.1.0"
authors = ["Dylan <dylan.dvorachek@gmail.com>"]

[workspace]

members = [
    "physics",
    "thread_pool",
    ]

[dependencies]

physics = { path = "./physics" }
thread_pool = { path = "./thread_pool" }
rand = "0.6"
